CREATE TABLE USUARIO (
  ID_USUARIO BIGINT NOT NULL GENERATED ALWAYS
        AS IDENTITY (START WITH 1, INCREMENT BY 1)
        CONSTRAINT PK_PESSOA PRIMARY KEY,
  LOGIN_USUARIO VARCHAR(100) NOT NULL,
  SENHA_USUARIO VARCHAR(100) NOT NULL,
  TIPO_USUARIO CHAR(1) NOT NULL
);

SELECT * FROM USUARIO

INSERT INTO USUARIO (LOGIN_USUARIO, SENHA_USUARIO, TIPO_USUARIO)
VALUES ('bclopes', '12345', 'G');
VALUES ('fabiosousa23', '67890', 'U');
VALUES ('vviana', '01234', 'T');

SELECT * FROM USUARIO WHERE LOGIN_USUARIO = 'bclopes' AND SENHA_USUARIO = '12345';
